using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Options;
using System.Collections.Concurrent;

namespace SF.Common.Infrastructure.Identity.Authorization.Permissions.AspNetIdentitiy {

    /// <summary>
    /// Custom <see cref="IAuthorizationPolicyProvider"/> implementation that dynamically creates
    /// authorization policies based on requested permission claim values.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This provider intercepts policy resolution requests during the authorization pipeline.
    /// If the requested policy name matches the format generated by 
    /// <see cref="PermissionAuthorizationEndpointConventionBuilderExtensions.RequirePermissions"/>,
    /// it will create a new policy that requires the corresponding <c>Permission</c> claims.
    /// </para>
    /// <para>
    /// Policies are cached in-memory to avoid repeated construction for the same permission set.
    /// </para>
    /// </remarks>
    public class PermissionAuthorizationPolicyProvider(
        IOptions<AuthorizationOptions> options
    ) : DefaultAuthorizationPolicyProvider(options) {
        private readonly ConcurrentDictionary<string, AuthorizationPolicy> _policyCache = new();

        /// <summary>
        /// Retrieves an <see cref="AuthorizationPolicy"/> for the specified name, creating it dynamically if needed.
        /// </summary>
        /// <param name="policyName">The name of the requested policy.</param>
        /// <returns>
        /// A matching <see cref="AuthorizationPolicy"/>, or <c>null</c> if the policy cannot be created.
        /// </returns>
        /// <remarks>
        /// This method:
        /// <list type="number">
        /// <item>Checks the cache for an existing policy.</item>
        /// <item>If not found, calls the base provider to look for a statically registered policy.</item>
        /// <item>If still not found, parses the <paramref name="policyName"/> and creates a new permission-based policy.</item>
        /// </list>
        /// </remarks>
        public override async Task<AuthorizationPolicy?> GetPolicyAsync(string policyName) {
            if (_policyCache.TryGetValue(policyName, out var cached))
                return cached;

            var existing = await base.GetPolicyAsync(policyName);
            if (existing == null) {
                // Expected policyName format: "Permission:CanCreateUsers,CanDeleteUsers"
                var parts = policyName.Split(':', 2);
                if (parts.Length == 2) {
                    var claimType = parts[0];
                    var claimValues = parts[1].Split(',', StringSplitOptions.RemoveEmptyEntries);

                    var newPolicy = new AuthorizationPolicyBuilder()
                        .AddAuthenticationSchemes(JwtBearerDefaults.AuthenticationScheme)
                        .RequireAuthenticatedUser()
                        .AddRequirements(new PermissionRequirement(claimType, claimValues))
                        .Build();

                    _policyCache[policyName] = newPolicy;
                    return newPolicy;
                }
            }

            return existing;
        }
    }
}
