<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Slascone.Client" Version="2.1.961" />
    <!-- Fixing CVE-2026-26171, CVE-2026-32203, CVE-2026-33116, CVE-2026-47302, CVE-2026-47304, CVE-2026-50525, CVE-2026-50527, CVE-2026-50648 -->
    <PackageReference Include="System.Security.Cryptography.Xml" Version="9.0.19" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Security\TGF.CA.Infrastructure.Secrets\TGF.CA.Infrastructure.Secrets.csproj" />
    <ProjectReference Include="..\TGF.CA.Infrastructure\TGF.CA.Infrastructure.csproj" />
  </ItemGroup>

</Project>
